### ISSUE TITLE
Constant crashes of rainmeter out of the box

### ISSUE THREAD

**Issue by naxim92** [keifufu/WebNowPlaying-Redux-Rainmeter#25]
After installation of WebNowPlaying v2.0.7 and enabling it got crashes of rainmeter

**Comment by keifufu** [comment]
send me the log from eventviewer

**Comment by naxim92** [comment]
```
Faulting application name: Rainmeter.exe, version: 4.5.20.3803, time stamp: 0x66cdefa9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4717, time stamp: 0x16b0a901
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0xa580
Faulting application start time: 0x01daff9ab66e478a
Faulting application path: C:\Program Files\Rainmeter\Rainmeter.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 461bdee8-9eff-47b7-a6b6-a0395cdeea92
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: Rainmeter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.HttpListenerException
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at WNPReduxAdapterLibrary.WNPHttpServer+<StartThreaded>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by keifufu** [comment]
someone on the rainmeter discord fixed the same problem like this, give it a shot and see if that's also your problem.
![image](https://github.com/user-attachments/assets/133676f9-30c0-46c0-9de5-8b2a1e25cd2f)

**Comment by naxim92** [comment]
No, still crashes

**Comment by keifufu** [comment]
tried a simple restart? anything else using the port 8974?

**Comment by naxim92** [comment]
I don't know what the reason but somehow after a time it starts work. My suggestion playing with firewall was helpful, thnx

**Comment by keifufu** [comment]
alright
